

services:
  achadoseperdidos:
    image: postgres
    container_name: achados-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=achados
      - POSTGRES_PASSWORD=perdidos
      - POSTGRES_DB=achadosEperdidos
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - default
  app:
    build: .
    container_name: achados-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - default


volumes:
  pgdata:
    driver: local